let config = require("./config").config


var forgotPasswordMailTemplate = {
    "from": '"Reset Password | Angular sample" <test.techugo@gmail.com>',
    "subject": ' Forgot Password email ',
    "html": '<!doctype html><html><head><title>Reset Password | Angular sample</title><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0; padding:0;"><div style="max-width:850px; margin:auto;"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0"><tr><td><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="margin:0 auto;"><tr><td align="center" style="font-size:16px; padding:20px 0; font-family:arial; background:#000;"><img src="{{baseUrl}}/assets/images/logo.png" width="281" height="80" alt="" /></td></tr></table></td></tr><tr><td valign="top"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="text-align:center; border:1px solid #ff9545; line-height:24px;"><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;"> Welcome to Angular sample!</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged {{email}}. Please click on the button below to activate and sign in to angular sample.</td></tr><tr><td style="padding:10px;"><div style="font-size:16px; font-family:arial; font-weight:bold; background-color:#ff9545;color:#fff; padding:10px;"><a href="{{link}}" target="_blank">Reset Password</a></div></td></tr><tr><td style="font-size:16px; padding:10px; font-family:arial;">You can also copy and paste the link below in your browser:</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;"><a href="#">{{link}}</a> </td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Thank You,</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Angular sample</td></tr><tr><td height="10"></td></tr></table></td></tr></table></div></body></html>'
}


var activationMailTemplate = {  
    "from": '"Angular sample" <pankaj.itdeveloper@gmail.com>',
    "subject": ' Account activation email ',    
    "html": '<!doctype html><html><head><title>Angular sample</title><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0; padding:0;"><div style="max-width:850px; margin:auto;"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0"><tr><td><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="margin:0 auto;"><tr><td align="center" style="font-size:16px; padding:20px 0; font-family:arial; background:#000;"><img src="{{baseUrl}}/assets/images/logo.png" width="281" height="80" alt="" /></td></tr></table></td></tr><tr><td valign="top"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="text-align:center; border:1px solid #ff9545; line-height:24px;"><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;"> Welcome to Angular sample!</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged {{email}}. Please click on the button below to activate and sign in to angular sample.</td></tr><tr><td style="padding:10px;"><div style="font-size:16px; font-family:arial; font-weight:bold; background-color:#ff9545;color:#fff; padding:10px;"><a href="{{link}}" target="_blank">Verify Email</a></div></td></tr><tr><td style="font-size:16px; padding:10px; font-family:arial;">You can also copy and paste the link below in your browser:</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;"><a href="#">{{link}}</a> </td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">Thank You,</td></tr><tr><td style="font-size:16px; padding:10px 0px; font-family:arial;">VE team</td></tr><tr><td height="10"></td></tr></table></td></tr></table></div></body></html>'
}

module.exports = {
    activationMailTemplate: activationMailTemplate,
    forgotPasswordMailTemplate : forgotPasswordMailTemplate
};

